ALTER TABLE CONVENIO RENAME COLUMN FLG_ATIVO TO FLG_DESATIVADO;
ALTER TABLE ATIVIDADE_CONVENIO RENAME COLUMN FLG_ATIVO TO FLG_DESATIVADO;
ALTER TABLE PLANO_CONVENIO RENAME COLUMN FLG_ATIVO TO FLG_DESATIVADO;