ALTER TABLE OUTROS_BENEFICIAVEIS ADD NUM_RG_OUTRO BIGINT NULL;

ALTER TABLE OUTROS_BENEFICIAVEIS ADD NUM_CPF_OUTRO BIGINT NULL;

UPDATE OUTROS_BENEFICIAVEIS SET NUM_RG_OUTRO = CAST (DES_RG AS BIGINT), NUM_CPF_OUTRO = CAST(DES_CPF AS BIGINT);

ALTER TABLE OUTROS_BENEFICIAVEIS DROP COLUMN DES_RG;

ALTER TABLE OUTROS_BENEFICIAVEIS DROP COLUMN DES_CPF;

CREATE OR REPLACE VIEW vw_outro_beneficiavel AS 
SELECT p.seq_pessoa AS seq_outro, p.nom_pessoa AS nom_outro, p.dat_nascimento_pessoa AS dat_nascimento_outro, p.sts_sexo_pessoa AS sts_sexo_outro, o.seq_associado, o.num_rg_outro, o.num_cpf_outro
   FROM pessoa p
NATURAL JOIN outros_beneficiaveis o;


CREATE OR REPLACE VIEW VW_BENEFICIARIO 
(SEQ_BENEFICIARIO, SEQ_ASSOCIADO, NOM_BENEFICIARIO, NUM_RG_BENEFICIARIO, NUM_CPF_BENEFICIARIO, TIPO)
AS 
SELECT SEQ_ASSOCIADO, SEQ_ASSOCIADO, NOM_ASSOCIADO, NUM_RG_ASSOCIADO, NUM_CPF_ASSOCIADO, 'TITULAR' AS TIPO
FROM VW_ASSOCIADO
UNION ALL
SELECT SEQ_CONJUGE, SEQ_ASSOCIADO, NOM_CONJUGE, NUM_RG_CONJUGE, NUM_CPF_CONJUGE, 'CONJUGE' AS TIPO 
FROM VW_CONJUGE
UNION ALL
SELECT SEQ_DEPENDENTE, SEQ_ASSOCIADO, NOM_DEPENDENTE, NUM_RG_DEPENDENTE, NUM_CPF_DEPENDENTE , 'DEPENDENTE' AS TIPO
FROM VW_DEPENDENTE
UNION ALL
SELECT SEQ_FILHO, SEQ_ASSOCIADO, NOM_FILHO, NUM_RG_FILHO, NUM_CPF_FILHO , 'FILHO' AS TIPO
FROM VW_FILHO
UNION ALL
SELECT SEQ_OUTRO, SEQ_ASSOCIADO, NOM_OUTRO, NUM_RG_OUTRO, NUM_CPF_OUTRO, 'OUTRO' AS TIPO
FROM VW_OUTRO_BENEFICIAVEL;