
ALTER TABLE LANCAMENTO DROP COLUMN TABELA_X;

ALTER TABLE LANCAMENTO DROP COLUMN NOM_CAMPO_X;

ALTER TABLE LANCAMENTO DROP COLUMN VAL_CAMPO_X;

CREATE TABLE FORMA_PAGAMENTO (
	SEQ_FORMA_PAGAMENTO	INT2 PRIMARY KEY NOT NULL,
	NOM_FORMA_PAGAMENTO	VARCHAR(30) NOT NULL
);

CREATE SEQUENCE SEQ_FORMA_PAGAMENTO START WITH 1 MAXVALUE 32000;

ALTER TABLE LANCAMENTO ADD SEQ_FORMA_PAGAMENTO INT2 NULL;

ALTER TABLE LANCAMENTO ADD CONSTRAINT FK_L_FORMA_PAGAMENTO FOREIGN KEY(SEQ_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (SEQ_FORMA_PAGAMENTO);

ALTER TABLE LANCAMENTO ADD DES_BANCO_CHEQUE_LANCAMENTO VARCHAR(30) NULL;

ALTER TABLE LANCAMENTO ADD NUM_AGENCIA_CHEQUE_LANCAMENTO VARCHAR(4) NULL;

ALTER TABLE LANCAMENTO ADD DIG_AGENCIA_CHEQUE_LANCAMENTO CHAR NULL;

ALTER TABLE LANCAMENTO ADD NUM_CONTA_CHEQUE_LANCAMENTO VARCHAR(30) NULL;

ALTER TABLE LANCAMENTO ADD DIG_CONTA_CHEQUE_LANCAMENTO CHAR NULL;

ALTER TABLE LANCAMENTO ADD DES_CHEQUE_LANCAMENTO VARCHAR(6) NULL;

----

CREATE TABLE DIRETOR_FINANCEIRO (
	SEQ_DIRETOR_FINANCEIRO	INT2 PRIMARY KEY NOT NULL,
	NOM_DIRETOR_FINANCEIRO	VARCHAR(50) NOT NULL,
	DAT_INICIO_GESTAO_DIRETOR_FINANCEIRO	DATE
);

----

ALTER TABLE DIRETOR_FINANCEIRO ALTER DAT_INICIO_GESTAO_DIRETOR_FINANCEIRO SET NOT NULL;

----

ALTER TABLE LANCAMENTO ALTER NUM_CONTA_CHEQUE_LANCAMENTO TYPE VARCHAR(10);

----

ALTER TABLE LANCAMENTO ALTER NUM_AGENCIA_CHEQUE_LANCAMENTO TYPE CHAR(4);

----

INSERT INTO FORMA_PAGAMENTO VALUES(NEXTVAL('SEQ_FORMA_PAGAMENTO'),'CHEQUE');

INSERT INTO FORMA_PAGAMENTO VALUES(NEXTVAL('SEQ_FORMA_PAGAMENTO'),'DINHEIRO');

INSERT INTO FORMA_PAGAMENTO VALUES(NEXTVAL('SEQ_FORMA_PAGAMENTO'),'DÉBITO AUTOMÁTICO');

INSERT INTO FORMA_PAGAMENTO VALUES(NEXTVAL('SEQ_FORMA_PAGAMENTO'),'DOC/TED');

INSERT INTO FORMA_PAGAMENTO VALUES(NEXTVAL('SEQ_FORMA_PAGAMENTO'),'TRANSFERÊNCIA');

INSERT INTO FORMA_PAGAMENTO VALUES(NEXTVAL('SEQ_FORMA_PAGAMENTO'),'PAGAMENTO VIA INTERNET BANKING');

----

INSERT INTO PARAMETROS VALUES ('FORMA_PAGTO_CHEQUE','1');

----