

CREATE TABLE FATURA_ARQUIVO (
	SEQ_FATURA_ARQUIVO	INTEGER NOT NULL,
	VAL_FATURA_ARQUIVO	NUMERIC(14,2) NOT NULL
);

ALTER TABLE FATURA_ARQUIVO ADD CONSTRAINT PK_FATURA_ARQUIVO PRIMARY KEY (SEQ_FATURA_ARQUIVO);



CREATE TABLE ITEM_FATURA_ARQUIVO
(
  SEQ_ITEM_FATURA_ARQUIVO 	INTEGER 		NOT NULL,
  NUM_CPF_BENEFICIARIO		BIGINT			NOT NULL,
  NOM_BENEFICIARIO		CHARACTER VARYING(60) 	NULL,
  FLG_TIPO_BENEFICIARIO		CHAR(1)			NULL,
  VAL_ITEM_FATURA_ARQUIVO	NUMERIC(14,2) 		NOT NULL,
  SEQ_FATURA_ARQUIVO		INTEGER 		NOT NULL
);

ALTER TABLE ITEM_FATURA_ARQUIVO ADD CONSTRAINT PK_ITEM_FATURA_ARQUIVO PRIMARY KEY (SEQ_ITEM_FATURA_ARQUIVO);

ALTER TABLE ITEM_FATURA_ARQUIVO ADD CONSTRAINT FK_IFA_FATURA_ARQUIVO FOREIGN KEY (SEQ_FATURA_ARQUIVO) REFERENCES FATURA_ARQUIVO (SEQ_FATURA_ARQUIVO);

CREATE SEQUENCE SEQ_ITEM_FATURA_ARQUIVO START WITH 1;