

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('STATUS_FATURA_GERADA', '1');

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('STATUS_FATURA_VALIDADA', '2');



