-- select p.nom_pessoa from associado a, pessoa p

SELECT 	C.NOM_FANTASIA,
	PC.NOM_PLANO,
	T.NOM_PESSOA AS TITULAR,	
	B.NOM_PESSOA  AS BENEFICIARIO,
	CASE
		WHEN EXISTS (SELECT D.SEQ_PESSOA FROM DEPENDENTE D WHERE B.SEQ_PESSOA = D.SEQ_PESSOA) THEN 'DEPENDENTE'
		WHEN EXISTS (SELECT F.SEQ_PESSOA FROM PESSOA F WHERE B.SEQ_PESSOA = F.SEQ_PESSOA) THEN 'FILHO'
--		WHEN EXISTS (SELECT F.SEQ_PESSOA FROM PESSOA CONJUGE WHERE B.SEQ_PESSOA = F.SEQ_PESSOA) THEN 'FILHO'
		ELSE 'TITULAR'
	END AS RELACIONAMENTO,
	PC.VAL_PLANO
FROM 	PESSOA B, 
	ASSOCIADO A,
	PESSOA T,
	VINCULACAO_PLANO VP,
	PLANO_CONVENIO PC,
	CONVENIO C
WHERE	B.SEQ_PESSOA = VP.SEQ_PESSOA
AND	VP.SEQ_ASSOCIADO = A.SEQ_PESSOA
AND	VP.SEQ_PLANO = PC.SEQ_PLANO
AND	PC.SEQ_CONVENIO = C.SEQ_CONVENIO
AND	A.SEQ_PESSOA = T.SEQ_PESSOA
AND	VP.DAT_DESVINCULACAO IS NULL
AND	upper(B.NOM_PESSOA) LIKE '%' || upper('') || '%'
AND	(null IS NULL OR A.SEQ_PESSOA = null)
AND	C.SEQ_CONVENIO = 1
AND	(null IS NULL OR PC.SEQ_PLANO = null)
AND	('01/01/2010' IS NULL OR VP.DAT_VINCULACAO >= '01/01/2010')
AND	('31/12/2010' IS NULL OR VP.DAT_VINCULACAO <= '12/31/2010')


--SELECT * FROM VINCULACAO_PLANO



-- select * from associado


--select * from associado

--select * from plano_convenio