delete from parametros where nom_parametro  = 'CONTA_CONSIGNACAO_NUCRE';

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO)
VALUES ('CONTA_DEBITO_CUSTO_CONSIG', 1);

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO)
VALUES ('CONTA_CREDITO_MENSALIDADE', 1);