DELETE FROM PARAMETROS WHERE NOM_PARAMETRO = 'CONTA_DEBITO_CUSTO_CONSIG'

SELECT * FROM PARAMETROS

UPDATE PARAMETROS SET NOM_PARAMETRO = 'CONTA_CONSIGNACAO_NUCRE' WHERE NOM_PARAMETRO = 'CONTA_CREDITO_MENSALIDADE'

CREATE UNIQUE INDEX "IDX_MATRICULA_JUSTICA"
  ON associado
  USING btree
  (num_matricula_justica_associado);
