
INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('CONTA_CREDITO_MENSALIDADE', 1);
INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('CONTA_DEBITO_CUSTO_CONSIG', 1);

INSERT INTO ORIGEM_LANCAMENTO (SEQ_ORIGEM_LANCAMENTO, NOM_ORIGEM_LANCAMENTO, FLG_ATIVO_ORIGEM_LANCAMENTO, FLG_NAO_APAGAVEL_ORIGEM_LANCAMENTO)
VALUES ((SELECT NEXTVAL('SEQ_ORIGEM_LANCAMENTO')), 'ASSOCIADOS', B'0'::"bit", B'1'::"bit");

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('ORIGEM_ASSOCIADOS', (SELECT SEQ_ORIGEM_LANCAMENTO FROM ORIGEM_LANCAMENTO WHERE NOM_ORIGEM_LANCAMENTO = 'ASSOCIADOS'));


