
CREATE OR REPLACE VIEW VW_CONJUGE AS 
SELECT p.seq_pessoa AS SEQ_CONJUGE, p.nom_pessoa AS NOM_CONJUGE, p.dat_nascimento_pessoa AS dat_nascimento_CONJUGE, p.sts_sexo_pessoa AS sts_sexo_CONJUGE, C.num_rg_CONJUGE, C.NUM_CPF_CONJUGE, C.seq_associado
   FROM pessoa p
NATURAL JOIN CONJUGE C;

SELECT SEQ_CONJUGE, NOM_CONJUGE, DAT_NASCIMENTO_CONJUGE, STS_SEXO_CONJUGE, NUM_RG_CONJUGE, NUM_CPF_CONJUGE, SEQ_ASSOCIADO FROM VW_CONJUGE
WHERE SEQ_ASSOCIADO = ?


CREATE INDEX IDX_C_ASSOCIADO ON CONJUGE (SEQ_ASSOCIADO);


select * from conjuge