
CREATE TABLE ATIVIDADE_CONVENIO (
  SEQ_ATIVIDADE_CONVENIO 	INT2 		PRIMARY KEY	NOT NULL,
  NOM_ATIVIDADE_CONVENIO 	VARCHAR(30) 			NOT NULL,
  FLG_ATIVO 			CHAR(1) 	DEFAULT 'S'	NOT NULL
);

ALTER TABLE ATIVIDADE_CONVENIO ADD CONSTRAINT CHK_FLG_ATIVO CHECK (FLG_ATIVO IN ('S','N'));
ALTER TABLE ATIVIDADE_CONVENIO OWNER TO ASSERJUF;

COMMENT ON TABLE ATIVIDADE_CONVENIO IS 'Lista das atividades dos convênios da ASSERJUF.';

COMMENT ON COLUMN ATIVIDADE_CONVENIO.SEQ_ATIVIDADE_CONVENIO IS 'Chave de identificação da atividade.';
COMMENT ON COLUMN ATIVIDADE_CONVENIO.NOM_ATIVIDADE_CONVENIO IS 'Nome da atividade.';
COMMENT ON COLUMN ATIVIDADE_CONVENIO.FLG_ATIVO IS '"S" se estiver ativa, "N" se não estiver ativa.';

CREATE SEQUENCE SEQ_ATIVIDADE_CONVENIO START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_ATIVIDADE_CONVENIO OWNER TO ASSERJUF;

------------

CREATE TABLE CONVENIO (
  SEQ_CONVENIO 			INT2 		PRIMARY KEY 	NOT NULL,
  FLG_CATEGORIA 		CHAR(1)				NOT NULL,
  NOM_FANTASIA 			VARCHAR(30)			NOT NULL,
  NOM_RAZAO_SOCIAL 		VARCHAR(60)			NULL,
  SEQ_ATIVIDADE_CONVENIO 	INT2 				NOT NULL,
  DES_CNPJ 			VARCHAR(14) 			NULL,
  DES_LOGRADOURO 		VARCHAR(100) 			NULL,
  DES_COMPLEMENTO 		VARCHAR(100) 			NULL,
  NOM_BAIRRO 			VARCHAR(20) 			NULL,
  NOM_CIDADE 			VARCHAR(60) 			NULL,
  SEQ_ESTADO 			smallint 			NULL,
  DES_CEP 			VARCHAR(8) 			NULL,
  NOM_CONTATO 			VARCHAR(60) 			NULL,
  DES_TELEFONE 			VARCHAR(10) 			NOT NULL,
  DES_TELEFONE_ADICIONAL 	VARCHAR(10) 			NULL,
  DES_FAX 			VARCHAR(10) 			NULL,
  DES_EMAIL 			VARCHAR(100) 			NULL,
  DES_BENEFICIO 		VARCHAR(1024) 			NOT NULL,
  DES_CONVENIO 			VARCHAR(1024) 			NULL,
  NUM_DIA_FECHAMENTO 		SMALLINT 			NULL,
  NUM_FATOR_MES_VCTO 		SMALLINT			NULL,
  NUM_DIA_VCTO 			SMALLINT			NULL,
  FLG_ATIVO 			CHAR(1) 	DEFAULT 'S'	NOT NULL,
  FLG_TITULAR 			CHAR(1) 	DEFAULT 'S'	NOT NULL,
  FLG_FILHOS 			CHAR(1) 	DEFAULT 'N'	NOT NULL,
  FLG_DEPENDENTES 		CHAR(1) 	DEFAULT 'N'	NOT NULL,
  FLG_CONJUGE 			CHAR(1) 	DEFAULT 'N'	NOT NULL,
  FLG_OUTROS_BENEF 		CHAR(1)		DEFAULT 'N'	NOT NULL
);

ALTER TABLE CONVENIO ADD CONSTRAINT FK_C_ATIVIDADE_CONVENIO FOREIGN KEY (SEQ_ATIVIDADE_CONVENIO) REFERENCES ATIVIDADE_CONVENIO(SEQ_ATIVIDADE_CONVENIO);

ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_CATEGORIA CHECK (FLG_CATEGORIA IN ('N','F','V'));
ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_ATIVO CHECK (FLG_ATIVO IN ('S','N'));
ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_TITULAR CHECK (FLG_TITULAR IN ('S','N'));
ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_FILHOS CHECK (FLG_FILHOS IN ('S','N'));
ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_DEPENDENTES CHECK (FLG_DEPENDENTES IN ('S','N'));
ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_CONJUGE CHECK (FLG_CONJUGE IN ('S','N'));
ALTER TABLE CONVENIO ADD CONSTRAINT CHK_FLG_OUTROS_BENEF CHECK (FLG_OUTROS_BENEF IN ('S','N'));


ALTER TABLE CONVENIO OWNER TO ASSERJUF;

CREATE SEQUENCE SEQ_CONVENIO START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_CONVENIO OWNER TO ASSERJUF;

-- FALTAM OS COMENTÁRIOS DA TABELA CONVENIO E SUAS COLUNAS...

----------------------------------------------

CREATE TABLE PLANO_CONVENIO (
  SEQ_PLANO 			INT2 	PRIMARY KEY 	NOT NULL,
  SEQ_CONVENIO 			INT2 			NOT NULL,
  NOM_PLANO 			VARCHAR(30) 		NOT NULL,
  DES_PLANO 			VARCHAR(255) 		NULL,
  VAL_PLANO 			numeric(14,2)		NOT NULL,
  DAT_INICIO_VALOR 		DATE 			NOT NULL,
  FLG_ATIVO 			CHAR(1)	DEFAULT 'S'	NOT NULL,
  FLG_DEDUTIVEL 		CHAR(1) DEFAULT 'N' 	NOT NULL  
);


ALTER TABLE PLANO_CONVENIO ADD CONSTRAINT FK_PC_CONVENIO FOREIGN KEY (SEQ_CONVENIO) REFERENCES CONVENIO(SEQ_CONVENIO);
ALTER TABLE PLANO_CONVENIO ADD CONSTRAINT CHK_FLG_ATIVO CHECK (FLG_ATIVO IN ('S','N'));

ALTER TABLE PLANO_CONVENIO OWNER TO ASSERJUF;

CREATE SEQUENCE SEQ_PLANO_CONVENIO START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_PLANO_CONVENIO OWNER TO ASSERJUF;

CREATE TABLE HIST_VALOR_PLANO (
  SEQ_HIST_VALOR_PLANO 	INT4 	PRIMARY KEY 		NOT NULL,
  SEQ_PLANO 		INT2				NOT NULL,
  VAL_PLANO 		NUMERIC(14,3)			NOT NULL,
  DAT_INICIO 		DATE 				NOT NULL,
  DAT_CADASTRO 		DATE DEFAULT CURRENT_DATE	NOT NULL
);

ALTER TABLE HIST_VALOR_PLANO ADD CONSTRAINT FK_HVP_PLANO FOREIGN KEY (SEQ_PLANO) REFERENCES PLANO_CONVENIO(SEQ_PLANO);

ALTER TABLE HIST_VALOR_PLANO OWNER TO ASSERJUF;

CREATE SEQUENCE SEQ_HIST_VALOR_PLANO START WITH 1 MAXVALUE 2147483647;

ALTER TABLE SEQ_HIST_VALOR_PLANO OWNER TO ASSERJUF;

------------------

