
CREATE SEQUENCE SEQ_PESSOA START WITH 1 MAXVALUE 2147483647;

ALTER TABLE SEQ_PESSOA OWNER TO admin_asserjuf;

CREATE SEQUENCE SEQ_MUNICIPIO START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_MUNICIPIO OWNER TO admin_asserjuf;

CREATE SEQUENCE SEQ_ORGAO START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_ORGAO OWNER TO admin_asserjuf;

CREATE SEQUENCE SEQ_PROFISSAO START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_PROFISSAO OWNER TO admin_asserjuf;

CREATE SEQUENCE SEQ_SETOR START WITH 1 MAXVALUE 32767;

ALTER TABLE SEQ_SETOR OWNER TO admin_asserjuf;


