SELECT * FROM PARAMETROS


INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('SMTP_SERVER','mail.asserjuf.org.br');

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('SMTP_USER_ACCOUNT','sisjuf');

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('SMTP_USER_PWD','paulo321');

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('EMAIL_SISJUF','sisjuf@asserjuf.org.br');
