select a.seq_associado, a.nom_associado, a.nom_orgao_associado,
 a.nom_setor_associado, a.des_email_associado, e.dat_historico_evento_associado from vw_associado a natural join historico_evento_associado e left join vw_associado a2 on a.seq_contribuinte_associado = a2.seq_associado left join vw_dependente d on d.seq_dependente = a.seq_associado left join vw_filho f on f.seq_filho = a.seq_associado inner join historico_evento_associado e2 on a.seq_associado = e2.seq_associado 
where e.seq_tipo_evento = (select int2(str_val_parametro) from parametros where nom_parametro = 'TP_EVT_CADASTRO')  
and (a.seq_associado = 32 or 32 is null) 
and (upper(a.nom_associado) like '%' || upper(NULL) || '%' or NULL is null)
and (a.sts_sexo_associado = NULL  or NULL is null or NULL = '')  
and (a.dat_nascimento_associado >= NULL or NULL is null) 
and (a.dat_nascimento_associado <= NULL or NULL is null) 
and (e.dat_historico_evento_associado >= NULL or NULL is null) 
and (e.dat_historico_evento_associado <= NULL or NULL is null) 
and (a.num_rg_associado = NULL or NULL is null) 
and (a.num_cpf_associado = NULL or NULL is null) 
and (upper(a.des_logradouro_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.des_numero_endereco_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.des_complemento_endereco_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.des_bairro_associado) like '%' || upper(NULL) || '%' or NULL is null) and (a.num_cep_associado = NULL or NULL is null) 
and (a.seq_estado_endereco_associado = NULL  or NULL is null) and (upper(a.des_municipio_endereco_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (a.num_telefone_residencial_associado = NULL or NULL is null) and (a.num_telefone_comercial_associado = NULL or NULL is null) 
and (a.num_telefone_celular_associado = NULL or NULL is null) and (upper(a.des_email_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (a.seq_estado_naturalidade_associado = NULL  or NULL is null) and (upper(a.des_naturalidade_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (a.sts_estado_civil_associado = NULL or NULL is null or NULL = '')  and (upper(a.des_profissao_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (a.des_grupo_sanguineo_associado = NULL or NULL is null or NULL = '')   
and (a.sts_fator_rh_associado= NULL  or NULL is null or NULL = '')  and (upper(a.nom_pai_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.nom_mae_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.nom_conjuge_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (a.num_calcado_associado >= NULL or NULL is null) and (a.num_calcado_associado <= NULL or NULL is null) 
and (a.sts_situacao_justica_associado = NULL  or NULL is null or NULL = '')  and (upper(a.nom_orgao_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.nom_setor_associado) like '%' || upper(NULL) || '%' or NULL is null) and (a.seq_estado_setor_associado = NULL  or NULL is null)  
and (upper(a.nom_municipio_setor_associado) like '%' || upper(NULL) || '%' or NULL is null) 
and (upper(a.des_endereco_setor_associado) like '%' || upper(NULL) || '%' or NULL is null) and (a.num_telefone_setor_associado = NULL or NULL is null) 
and (a.num_ramal_setor_associado = NULL or NULL is null) 
and (a.num_matricula_justica_associado = NULL or NULL is null) and (a.sts_categoria_associado = NULL  or NULL is null or NULL = '')  
and ((upper(a2.nom_associado) like '%' || upper(NULL) || '%' or NULL is null) or (a2.nom_associado is null and (NULL is null or NULL = ''))) 
and (a.sts_recebe_jornal_associado = NULL or NULL is null or '' = NULL) and (a.seq_banco = NULL or NULL is null) 
and (upper(a.num_agencia_associado) like '%' || upper(NULL) || '%' or NULL is null) and (a.dig_agencia_associado = NULL or NULL is null or '' = NULL) 
and (upper(a.num_conta_associado) like '%' || upper(NULL) || '%' or NULL is null) and (a.dig_conta_associado = NULL or NULL is null or '' = NULL) 
and (upper(d.nom_dependente) like '%' || upper(NULL) || '%' or NULL is null) and ((exists (select d2.seq_dependente from vw_dependente d2 where d2.seq_associado = a.seq_associado)) or NULL is null or NULL = '') 
and ((exists (select f2.seq_filho from vw_filho f2 where f2.seq_associado = a.seq_associado)) or NULL is null or NULL = '') 
and (d.num_rg_dependente = NULL or NULL is null) 
and (d.dat_nascimento_dependente >= NULL or NULL is null) 
and (d.dat_nascimento_dependente <= NULL or NULL is null) 
and (d.sts_sexo_dependente = NULL or NULL is null or NULL = '') 
and (d.seq_parentesco  = NULL  or NULL is null) and (upper(f.nom_filho) like '%' || upper(NULL) || '%' or NULL is null) 
and (f.dat_nascimento_filho >= NULL or NULL is null) and (f.dat_nascimento_filho <= NULL or NULL is null) 
and (f.sts_sexo_filho = NULL or NULL is null or NULL = '') 
and ((select h2.seq_tipo_evento from historico_evento_associado h2 where h2.seq_associado = a.seq_associado order by h2.dat_historico_evento_associado desc limit 1) <>  (select int2(str_val_parametro) from parametros where nom_parametro = 'TP_EVT_CANCELAMENTO') or NULL = 'S') 
and ((e2.seq_tipo_evento = NULL and e2.dat_historico_evento_associado >= NULL and e2.dat_historico_evento_associado <= NULL) or NULL is null)
and (filtro_val_mensalidade(NULL, NULL, a.seq_associado) or (NULL is null and NULL is null)) 
and a.dat_exclusao_associado is null 
group by a.seq_associado, a.nom_associado, a.nom_orgao_associado, a.nom_setor_associado, e.dat_historico_evento_associado, a.des_email_associado