INSERT INTO ESTADO VALUES (14, 'ACRE', 'AC');
INSERT INTO ESTADO VALUES (3, 'ALAGOAS', 'AL');
INSERT INTO ESTADO VALUES (10, 'AMAPÁ', 'AP');
INSERT INTO ESTADO VALUES (11, 'AMAZONAS', 'AM');
INSERT INTO ESTADO VALUES (1, 'BAHIA', 'BA');
INSERT INTO ESTADO VALUES (8, 'CEARÁ', 'CE');
INSERT INTO ESTADO VALUES (27, 'DISTRITO FEDERAL', 'DF');
INSERT INTO ESTADO VALUES (21, 'ESPÍRITO SANTO', 'ES');
INSERT INTO ESTADO VALUES (17, 'GOIÁS', 'GO');
INSERT INTO ESTADO VALUES (9, 'MARANHÃO', 'MA');
INSERT INTO ESTADO VALUES (18, 'MATO GROSSO', 'MT');
INSERT INTO ESTADO VALUES (19, 'MATO GROSSO DO SUL', 'MS');
INSERT INTO ESTADO VALUES (20, 'MINAS GERAIS', 'MG');
INSERT INTO ESTADO VALUES (16, 'PARÁ', 'PA');
INSERT INTO ESTADO VALUES (5, 'PARAÍBA', 'PB');
INSERT INTO ESTADO VALUES (25, 'PARANÁ', 'PR');
INSERT INTO ESTADO VALUES (4, 'PERNAMBUCO', 'PE');
INSERT INTO ESTADO VALUES (7, 'PIAUÍ', 'PI');
INSERT INTO ESTADO VALUES (22, 'RIO DE JANEIRO', 'RJ');
INSERT INTO ESTADO VALUES (6, 'RIO GRANDE DO NORTE', 'RN');
INSERT INTO ESTADO VALUES (26, 'RIO GRANDE DO SUL', 'RS');
INSERT INTO ESTADO VALUES (13, 'RONDÔNIA', 'RO');
INSERT INTO ESTADO VALUES (12, 'RORAIMA', 'RR');
INSERT INTO ESTADO VALUES (24, 'SANTA CATARINA', 'SC');
INSERT INTO ESTADO VALUES (23, 'SÃO PAULO', 'SP');
INSERT INTO ESTADO VALUES (2, 'SERGIPE', 'SE');
INSERT INTO ESTADO VALUES (15, 'TOCANTINS', 'TO');



