
ALTER TABLE LANCAMENTO DROP COLUMN SEQ_FORMA_PAGAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD SEQ_FORMA_PAGAMENTO INT2;


ALTER TABLE LANCAMENTO DROP COLUMN DES_BANCO_CHEQUE_LANCAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD DES_BANCO_CHEQUE_BAIXA_LANCAMENTO VARCHAR(30);


ALTER TABLE LANCAMENTO DROP COLUMN NUM_AGENCIA_CHEQUE_LANCAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD NUM_AGENCIA_CHEQUE_BAIXA_LANCAMENTO VARCHAR(4);


ALTER TABLE LANCAMENTO DROP COLUMN DIG_AGENCIA_CHEQUE_LANCAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD DIG_AGENCIA_CHEQUE_BAIXA_LANCAMENTO CHAR;


ALTER TABLE LANCAMENTO DROP COLUMN NUM_CONTA_CHEQUE_LANCAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD NUM_CONTA_CHEQUE_BAIXA_LANCAMENTO VARCHAR(10);


ALTER TABLE LANCAMENTO DROP COLUMN DIG_CONTA_CHEQUE_LANCAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD DIG_CONTA_CHEQUE_BAIXA_LANCAMENTO CHAR;



ALTER TABLE LANCAMENTO DROP COLUMN DES_CHEQUE_LANCAMENTO;

ALTER TABLE BAIXA_LANCAMENTO ADD NUM_CHEQUE_BAIXA_LANCAMENTO VARCHAR(10);