INSERT INTO STATUS_FATURA VALUES (1, 'GERADA');

INSERT INTO STATUS_FATURA VALUES (2, 'VALIDADA');

INSERT INTO STATUS_FATURA VALUES (3, 'CANCELADA');

INSERT INTO PARAMETROS VALUES ('STATUS_FATURA_CANCELADA', '3');
