

INSERT INTO ORIGEM_LANCAMENTO (SEQ_ORIGEM_LANCAMENTO, NOM_ORIGEM_LANCAMENTO, FLG_ATIVO_ORIGEM_LANCAMENTO, FLG_NAO_APAGAVEL_ORIGEM_LANCAMENTO)
VALUES (NEXTVAL('SEQ_ORIGEM_LANCAMENTO'), 'CONVÊNIOS', B'0', B'1');

INSERT INTO PARAMETROS (NOM_PARAMETRO, STR_VAL_PARAMETRO) VALUES ('ORIGEM_CONVENIOS', (SELECT SEQ_ORIGEM_LANCAMENTO FROM ORIGEM_LANCAMENTO WHERE NOM_ORIGEM_LANCAMENTO = 'CONVÊNIOS'));