CREATE TABLE VINCULACAO_PLANO (
  SEQ_VINCULACAO	INTEGER		PRIMARY KEY	NOT NULL,
  SEQ_PESSOA 		INTEGER 			NOT NULL,
  SEQ_ASSOCIADO 	INTEGER 			NOT NULL,
  SEQ_PLANO 		INT2 				NOT NULL,
  DAT_VINCULACAO 	DATE 				NOT NULL,
  DAT_DESVINCULACAO 	DATE 				NULL
);

ALTER TABLE VINCULACAO_PLANO ADD CONSTRAINT FK_VP_PESSOA FOREIGN KEY (SEQ_PESSOA) REFERENCES PESSOA (SEQ_PESSOA);
ALTER TABLE VINCULACAO_PLANO ADD CONSTRAINT FK_VP_ASSOCIADO FOREIGN KEY (SEQ_ASSOCIADO) REFERENCES ASSOCIADO (SEQ_PESSOA);
ALTER TABLE VINCULACAO_PLANO ADD CONSTRAINT FK_VP_PLANO FOREIGN KEY (SEQ_PLANO) REFERENCES PLANO_CONVENIO (SEQ_PLANO);

ALTER TABLE VINCULACAO_PLANO OWNER TO ASSERJUF;

CREATE SEQUENCE SEQ_VINCULACAO START WITH 1 MAXVALUE 2147483647;

ALTER TABLE SEQ_VINCULACAO OWNER TO ASSERJUF;


CREATE TABLE HIST_VINCULACAO_PLANO (
  SEQ_HIST_VINCULACAO_PLANO	INTEGER	PRIMARY KEY	NOT NULL,
  SEQ_VINCULACAO 		INTEGER 		NOT NULL,
  DAT_VINCULACAO 	DATE 				NOT NULL,
  DAT_DESVINCULACAO 	DATE 				NOT NULL
);

ALTER TABLE HIST_VINCULACAO_PLANO ADD CONSTRAINT FK_HVP_VINCULACAO FOREIGN KEY (SEQ_VINCULACAO) REFERENCES VINCULACAO_PLANO (SEQ_VINCULACAO);

ALTER TABLE HIST_VINCULACAO_PLANO OWNER TO ASSERJUF;

CREATE SEQUENCE SEQ_HIST_VINCULACAO_PLANO START WITH 1 MAXVALUE 2147483647;

ALTER TABLE SEQ_HIST_VINCULACAO_PLANO OWNER TO ASSERJUF;


CREATE TABLE ITEM_FATURA (
  SEQ_ITEM_FATURA 	INTEGER 	PRIMARY KEY	NOT NULL,
  SEQ_VINCULACAO 	INTEGER 			NOT NULL,
  SEQ_FATURA 		INT4	 			NOT NULL,
  VAL_ITEM_FATURA 	NUMERIC(14,2)			NOT NULL
);

ALTER TABLE ITEM_FATURA ADD CONSTRAINT FK_IF_VINCULACAO FOREIGN KEY (SEQ_VINCULACAO) REFERENCES VINCULACAO_PLANO (SEQ_VINCULACAO);
ALTER TABLE ITEM_FATURA ADD CONSTRAINT FK_IF_FATURA FOREIGN KEY (SEQ_FATURA) REFERENCES FATURA (SEQ_FATURA);

ALTER TABLE ITEM_FATURA OWNER TO ASSERJUF;
CREATE SEQUENCE SEQ_ITEM_FATURA START WITH 1 MAXVALUE 2147483647;
ALTER TABLE SEQ_ITEM_FATURA OWNER TO ASSERJUF;


CREATE TABLE LANCAMENTO_FATURA (
  SEQ_LANCAMENTO 	BIGINT	 		NOT NULL,
  SEQ_FATURA 		INTEGER 	 	NOT NULL
);

ALTER TABLE LANCAMENTO_FATURA ADD CONSTRAINT FK_LANCAMENTO_FATURA PRIMARY KEY (SEQ_LANCAMENTO, SEQ_FATURA);

ALTER TABLE LANCAMENTO_FATURA ADD CONSTRAINT FK_LF_LANCAMENTO 	FOREIGN KEY (SEQ_LANCAMENTO) 	REFERENCES LANCAMENTO (SEQ_LANCAMENTO);
ALTER TABLE LANCAMENTO_FATURA ADD CONSTRAINT FK_LF_FATURA 	FOREIGN KEY (SEQ_FATURA) 	REFERENCES FATURA (SEQ_FATURA);

ALTER TABLE LANCAMENTO_FATURA OWNER TO ASSERJUF;


CREATE TABLE LANCAMENTO_ITEM_FATURA (
  SEQ_LANCAMENTO BIGINT 	NOT NULL,
  SEQ_ITEM_FATURA INTEGER 	NOT NULL
);

ALTER TABLE LANCAMENTO_ITEM_FATURA ADD CONSTRAINT FK_LANCAMENTO_ITEM_FATURA 	PRIMARY KEY (SEQ_LANCAMENTO, SEQ_ITEM_FATURA);
ALTER TABLE LANCAMENTO_ITEM_FATURA ADD CONSTRAINT FK_LIF_LANCAMENTO 		FOREIGN KEY (SEQ_LANCAMENTO) 	REFERENCES LANCAMENTO (SEQ_LANCAMENTO);
ALTER TABLE LANCAMENTO_ITEM_FATURA ADD CONSTRAINT FK_LIF_ITEM_FATURA 		FOREIGN KEY (SEQ_ITEM_FATURA) 	REFERENCES ITEM_FATURA (SEQ_ITEM_FATURA);

ALTER TABLE LANCAMENTO_ITEM_FATURA OWNER TO ASSERJUF;



CREATE TABLE OUTROS_BENEFICIAVEIS (
  SEQ_PESSOA 	INTEGER PRIMARY KEY 	NOT NULL,
  SEQ_ASSOCIADO INTEGER 		NOT NULL,
  DES_RG 	VARCHAR(20) 		NULL,
  DES_CPF 	VARCHAR(11) 		NULL
);

ALTER TABLE OUTROS_BENEFICIAVEIS ADD CONSTRAINT FK_OB_PESSOA 	FOREIGN KEY (SEQ_PESSOA) 	REFERENCES PESSOA (SEQ_PESSOA);
ALTER TABLE OUTROS_BENEFICIAVEIS ADD CONSTRAINT FK_LB_ASSOCIADO	FOREIGN KEY (SEQ_ASSOCIADO) 	REFERENCES ASSOCIADO (SEQ_PESSOA);

ALTER TABLE OUTROS_BENEFICIAVEIS OWNER TO ASSERJUF;

ALTER TABLE PESSOA ADD FLG_DEDUTIVEL CHAR(1) DEFAULT 'N' NOT NULL;
ALTER TABLE PESSOA ADD CONSTRAINT CHK_FLG_DEDUTIVEL CHECK (FLG_DEDUTIVEL IN ('S', 'N'));

CREATE TABLE CONJUGE (
  SEQ_PESSOA 	INTEGER 	PRIMARY KEY 	NOT NULL,
  DES_RG 	VARCHAR(20) 			NULL,
  DES_CPF 	VARCHAR(11) 			NULL
);

ALTER TABLE CONJUGE ADD SEQ_ASSOCIADO INTEGER NOT NULL;

ALTER TABLE CONJUGE ADD CONSTRAINT FK_C_ASSOCIADO FOREIGN KEY (SEQ_ASSOCIADO) REFERENCES ASSOCIADO (SEQ_PESSOA);

ALTER TABLE CONJUGE ADD CONSTRAINT FK_C_PESSOA FOREIGN KEY (SEQ_PESSOA) REFERENCES PESSOA (SEQ_PESSOA);

ALTER TABLE CONJUGE OWNER TO ASSERJUF;

