
SELECT 	F.SEQ_FATURA, B.NUM_CPF_BENEFICIARIO, B.NOM_BENEFICIARIO, IF.VAL_ITEM_FATURA, 'NÃO ENCONTRADO NO ARQUIVO' AS TIPO_INCONSISTENCIA
FROM 	FATURA F, ITEM_FATURA IF, VINCULACAO_PLANO VP, VW_BENEFICIARIO B
WHERE 	F.SEQ_FATURA = IF.SEQ_FATURA
AND	IF.SEQ_VINCULACAO = VP.SEQ_VINCULACAO
AND	VP.SEQ_PESSOA = B.SEQ_BENEFICIARIO
AND	B.NUM_CPF_BENEFICIARIO NOT IN (
	SELECT 	IFA.NUM_CPF_BENEFICIARIO
	FROM 	ITEM_FATURA_ARQUIVO IFA, FATURA_ARQUIVO FA
	WHERE 	IFA.SEQ_FATURA_ARQUIVO = FA.SEQ_FATURA_ARQUIVO
	AND     IFA.NUM_CPF_BENEFICIARIO = B.NUM_CPF_BENEFICIARIO
	AND	FA.SEQ_FATURA_ARQUIVO = F.SEQ_FATURA
)
AND 	F.SEQ_FATURA = 24
UNION ALL
SELECT 	FA.SEQ_FATURA_ARQUIVO, IFA.NUM_CPF_BENEFICIARIO, IFA.NOM_BENEFICIARIO, IFA.VAL_ITEM_FATURA_ARQUIVO, 'NÃO ENCONTRADO NA BASE' AS TIPO_INCONSISTENCIA
FROM	FATURA_ARQUIVO FA, ITEM_FATURA_ARQUIVO IFA
WHERE 	FA.SEQ_FATURA_ARQUIVO = IFA.SEQ_FATURA_ARQUIVO
AND	IFA.NUM_CPF_BENEFICIARIO NOT IN (
	SELECT 	B.NUM_CPF_BENEFICIARIO
	FROM 	FATURA F, ITEM_FATURA IF, VINCULACAO_PLANO VP, VW_BENEFICIARIO B
	WHERE 	F.SEQ_FATURA = IF.SEQ_FATURA
	AND	IF.SEQ_VINCULACAO = VP.SEQ_VINCULACAO
	AND	VP.SEQ_PESSOA = B.SEQ_BENEFICIARIO
	AND	F.SEQ_FATURA = FA.SEQ_FATURA_ARQUIVO
)
AND FA.SEQ_FATURA_ARQUIVO = 24
UNION ALL
SELECT 	F.SEQ_FATURA, B.NUM_CPF_BENEFICIARIO, B.NOM_BENEFICIARIO, IF.VAL_ITEM_FATURA, 'VALOR NÃO BATE' AS TIPO_INCONSISTENCIA
FROM	FATURA F, ITEM_FATURA IF, VINCULACAO_PLANO VP, VW_BENEFICIARIO B, ITEM_FATURA_ARQUIVO IFA
WHERE 	F.SEQ_FATURA = IF.SEQ_FATURA
AND	IF.SEQ_VINCULACAO = VP.SEQ_VINCULACAO
AND	VP.SEQ_PESSOA = B.SEQ_BENEFICIARIO
AND	IFA.SEQ_FATURA_ARQUIVO = F.SEQ_FATURA
AND	IFA.NUM_CPF_BENEFICIARIO = B.NUM_CPF_BENEFICIARIO
AND	IFA.VAL_ITEM_FATURA_ARQUIVO <> IF.VAL_ITEM_FATURA
AND 	F.SEQ_FATURA = 24
ORDER BY SEQ_FATURA, NUM_CPF_BENEFICIARIO

--SELECT * FROM VW_BENEFICIARIO
