ALTER TABLE DEPENDENTE ADD NUM_CPF_DEPENDENTE BIGINT NULL;

ALTER TABLE FILHO ADD NUM_CPF_FILHO BIGINT NULL;

DROP TABLE CONJUGE;

CREATE TABLE CONJUGE (
	SEQ_PESSOA	INTEGER	PRIMARY KEY NOT NULL,
	NUM_CPF_CONJUGE	BIGINT		    NULL,
	NUM_RG_CONJUGE	BIGINT		    NULL,
	SEQ_ASSOCIADO	INTEGER		    NOT NULL
);


ALTER TABLE CONJUGE ADD FOREIGN KEY (SEQ_ASSOCIADO) REFERENCES ASSOCIADO (SEQ_PESSOA);

--SELECT * FROM ASSOCIADO


