INSERT INTO TIPO_EVENTO (SEQ_TIPO_EVENTO, NOM_TIPO_EVENTO) VALUES (1, 'CADASTRO');

INSERT INTO TIPO_EVENTO (SEQ_TIPO_EVENTO, NOM_TIPO_EVENTO) VALUES (2, 'CANCELAMENTO');

INSERT INTO TIPO_EVENTO (SEQ_TIPO_EVENTO, NOM_TIPO_EVENTO) VALUES (3, 'REATIVAÇÃO');


ALTER TABLE HISTORICO_EVENTO_ASSOCIADO ADD CONSTRAINT fk_HEA_TIPO_EVENTO FOREIGN KEY (SEQ_TIPO_EVENTO)
      REFERENCES TIPO_EVENTO (seq_TIPO_EVENTO); 