DELETE FROM PARENTESCO;

INSERT INTO PARENTESCO VALUES (1,  'FILHO(A)');

INSERT INTO PARENTESCO VALUES (2,  'IRMÃO(Ã)');

INSERT INTO PARENTESCO VALUES (3,  'PRIMO(A)');

INSERT INTO PARENTESCO VALUES (4,  'TIO(A)');

INSERT INTO PARENTESCO VALUES (5,  'AVÔ(Ó)');

INSERT INTO PARENTESCO VALUES (6,  'MARIDO');

INSERT INTO PARENTESCO VALUES (7,  'ESPOSA');

INSERT INTO PARENTESCO VALUES (8,  'ENTEADO(A)');

INSERT INTO PARENTESCO VALUES (9,  'NETO(A)');

INSERT INTO PARENTESCO VALUES (10, 'PAI');

INSERT INTO PARENTESCO VALUES (11, 'MÃE');
