CREATE TABLE LANCAMENTO_ASSOCIADO (
	SEQ_ASSOCIADO	INT4	NOT NULL,
	SEQ_LANCAMENTO	INT8	NOT NULL,	
	CONSTRAINT PK_LANCAMENTO_ASSOCIADO PRIMARY KEY (SEQ_ASSOCIADO, SEQ_LANCAMENTO),
	CONSTRAINT FK_LANCAMENTO_ASSOCIADO_ASSOCIADO FOREIGN KEY (SEQ_ASSOCIADO) REFERENCES ASSOCIADO(SEQ_PESSOA),
	CONSTRAINT FK_LANCAMENTO_ASSOCIADO_LANCAMENTO FOREIGN KEY (SEQ_LANCAMENTO) REFERENCES LANCAMENTO(SEQ_LANCAMENTO)
)
