

BEGIN TRANSACTION;

INSERT INTO PESSOA (SEQ_PESSOA, NOM_PESSOA, DAT_NASCIMENTO_PESSOA, STS_SEXO_PESSOA, FLG_DEDUTIVEL)
SELECT NEXTVAL('SEQ_PESSOA'), ASSOCIADO.NOM_CONJUGE_ASSOCIADO || '_' || ASSOCIADO.SEQ_PESSOA, PESSOA.DAT_NASCIMENTO_PESSOA, 
	CASE WHEN PESSOA.STS_SEXO_PESSOA= 'M' THEN 'F'
	ELSE 'M' 
	END AS SEXO_CONJUGE,
	'S'
FROM ASSOCIADO, PESSOA
WHERE ASSOCIADO.NOM_CONJUGE_ASSOCIADO IS NOT NULL AND ASSOCIADO.NOM_CONJUGE_ASSOCIADO <> ''
AND PESSOA.SEQ_PESSOA = ASSOCIADO.SEQ_PESSOA;


INSERT INTO CONJUGE (SEQ_PESSOA, NUM_CPF_CONJUGE, NUM_RG_CONJUGE, SEQ_ASSOCIADO)
SELECT C.SEQ_PESSOA, NULL, NULL, A.SEQ_PESSOA FROM
	PESSOA A,
	PESSOA C,
	ASSOCIADO ASS
WHERE ASS.NOM_CONJUGE_ASSOCIADO || '_' || ASS.SEQ_PESSOA = C.NOM_PESSOA
AND ASS.SEQ_PESSOA = A.SEQ_PESSOA;

COMMIT;
