CREATE SEQUENCE SEQ_FUNCIONALIDADE;
CREATE TABLE FUNCIONALIDADE (
  SEQ_FUNCIONALIDADE INTEGER NOT NULL,
  NOME VARCHAR(50) NULL,
  DESCRICAO VARCHAR(100) NULL,
  PRIMARY KEY(SEQ_FUNCIONALIDADE)
);

CREATE SEQUENCE SEQ_LINK;
CREATE TABLE LINK_FUNCAO (
  SEQ_LINK INTEGER NOT NULL,
  URL VARCHAR(100) NULL UNIQUE,
  DESCRICAO VARCHAR(100) NULL,
  TIPO CHAR(1) NULL,
  PRIMARY KEY(SEQ_LINK)
);

CREATE SEQUENCE SEQ_FUNCAO;
CREATE TABLE FUNCAO (
  SEQ_FUNCAO INTEGER NOT NULL,
  SEQ_LINK INTEGER NOT NULL,
  NOME VARCHAR(50) NULL UNIQUE,
  DESCRICAO VARCHAR(100) NULL,
  PRIMARY KEY(SEQ_FUNCAO),
  FOREIGN KEY(SEQ_LINK)
    REFERENCES LINK_FUNCAO(SEQ_LINK)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE SEQUENCE SEQ_PERFIL;
CREATE TABLE PERFIL (
  SEQ_PERFIL INTEGER NOT NULL,
  NOME VARCHAR(50) NULL UNIQUE,
  DESCRICAO VARCHAR(100) NULL,
  PRIMARY KEY(SEQ_PERFIL)
);

CREATE SEQUENCE SEQ_USUARIO;
CREATE TABLE USUARIO (
  SEQ_USUARIO INTEGER NOT NULL,
  SEQ_PERFIL INTEGER NOT NULL,
  NOME VARCHAR(100) NULL,
  LOGIN VARCHAR(15) NULL UNIQUE,
  SENHA VARCHAR(100) NULL,
  PRIMARY KEY(SEQ_USUARIO),
  FOREIGN KEY(SEQ_PERFIL)
    REFERENCES PERFIL(SEQ_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FUNCAO_FUNCIONALIDADE (
  SEQ_FUNCAO INTEGER NOT NULL,
  SEQ_FUNCIONALIDADE INTEGER NOT NULL,
  PRIMARY KEY(SEQ_FUNCAO, SEQ_FUNCIONALIDADE),
  FOREIGN KEY(SEQ_FUNCAO)
    REFERENCES FUNCAO(SEQ_FUNCAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SEQ_FUNCIONALIDADE)
    REFERENCES FUNCIONALIDADE(SEQ_FUNCIONALIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PERFIL_FUNCAO (
  SEQ_PERFIL INTEGER NOT NULL,
  SEQ_FUNCAO INTEGER NOT NULL,
  PRIMARY KEY(SEQ_PERFIL, SEQ_FUNCAO),
  FOREIGN KEY(SEQ_FUNCAO)
    REFERENCES FUNCAO(SEQ_FUNCAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SEQ_PERFIL)
    REFERENCES PERFIL(SEQ_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PERFIL_FUNCIONALIDADE (
  SEQ_FUNCIONALIDADE INTEGER NOT NULL,
  SEQ_PERFIL INTEGER NOT NULL,
  PRIMARY KEY(SEQ_FUNCIONALIDADE, SEQ_PERFIL),
  FOREIGN KEY(SEQ_PERFIL)
    REFERENCES PERFIL(SEQ_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SEQ_FUNCIONALIDADE)
    REFERENCES FUNCIONALIDADE(SEQ_FUNCIONALIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USUARIO_FUNCAO (
  SEQ_USUARIO INTEGER NOT NULL,
  SEQ_FUNCAO INTEGER NOT NULL,
  PRIMARY KEY(SEQ_USUARIO, SEQ_FUNCAO),
  FOREIGN KEY(SEQ_FUNCAO)
    REFERENCES FUNCAO(SEQ_FUNCAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SEQ_USUARIO)
    REFERENCES USUARIO(SEQ_USUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USUARIO_FUNCIONALIDADE (
  SEQ_USUARIO INTEGER NOT NULL,
  SEQ_FUNCIONALIDADE INTEGER NOT NULL,
  PRIMARY KEY(SEQ_USUARIO, SEQ_FUNCIONALIDADE),
  FOREIGN KEY(SEQ_USUARIO)
    REFERENCES USUARIO(SEQ_USUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SEQ_FUNCIONALIDADE)
    REFERENCES FUNCIONALIDADE(SEQ_FUNCIONALIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

