name: ANT

on:
  push:
    branches: 
      - teste-actions
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile ./SisjufNovo/apps/app_web_sisjuf/build-github.xml
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{secrets.PROD_HOST}}
        username: ${{secrets.PROD_USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 23
        script: ls -la
